import type { PoiEntry } from './types'
import { profileLinks } from './profile'

export const portfolioGlossary: PoiEntry[] = [
  {
    id: 'company-hq',
    name: 'Company HQ',
    kind: 'company',
    status: 'live',
    description:
      'Das Hauptgebaeude deiner Firma: Leistungen, Cases, Kontakt und wie man mit dir arbeitet.',
    accentColor: '#e59d39',
    spriteHint: 'hq_gold',
    dialog: {
      title: 'Company HQ',
      body: 'Hier sieht man dein Business-Profil, Leistungen und wie man ein Projekt mit dir startet.',
    },
    tags: ['company', 'services', 'contact'],
    district: 'Founder District',
    world: {
      x: 240,
      y: 112,
      width: 112,
      height: 88,
      interactRadius: 86,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'company-website',
        label: 'Firmenwebsite oeffnen',
        type: 'open_link',
        href: profileLinks.companyWebsite,
        confirmMessage: 'Zur Firmenwebsite wechseln?',
      },
      {
        id: 'company-services',
        label: 'Leistungen anzeigen',
        type: 'open_modal',
      },
    ],
  },
  {
    id: 'linkedin-house',
    name: 'LinkedIn Haus',
    kind: 'external_link',
    status: 'live',
    description: 'Lebenslauf und professionelle Timeline sind ueber LinkedIn erreichbar.',
    accentColor: '#0a66c2',
    spriteHint: 'house_linkedin',
    dialog: {
      title: 'LinkedIn',
      body: 'Hier geht es direkt zu deinem Lebenslauf und professionellen Profil.',
    },
    tags: ['linkedin', 'cv', 'career'],
    district: 'Career Street',
    world: {
      x: 704,
      y: 132,
      width: 96,
      height: 80,
      interactRadius: 82,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'linkedin-open',
        label: 'LinkedIn oeffnen',
        type: 'open_link',
        href: profileLinks.linkedin,
        confirmMessage: 'LinkedIn in neuem Tab oeffnen?',
      },
    ],
  },
  {
    id: 'github-house',
    name: 'GitHub Werkstatt',
    kind: 'external_link',
    status: 'live',
    description: 'Code, Repositories und Open-Source-Projekte als technischer Nachweis.',
    accentColor: '#24292f',
    spriteHint: 'house_github',
    dialog: {
      title: 'GitHub Werkstatt',
      body: 'Hier sehen Besucher deinen Code, Commit-Historie und aktive Projekte.',
    },
    tags: ['github', 'code', 'opensource'],
    district: 'Career Street',
    world: {
      x: 844,
      y: 174,
      width: 96,
      height: 80,
      interactRadius: 82,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'github-open',
        label: 'GitHub oeffnen',
        type: 'open_link',
        href: profileLinks.github,
        confirmMessage: 'GitHub in neuem Tab oeffnen?',
      },
    ],
  },
  {
    id: 'projects-lab',
    name: 'Fun Projects Lab',
    kind: 'project_showcase',
    status: 'live',
    description: 'Spielerische und kreative Projekte mit kurzen Erklaerungen und Links.',
    accentColor: '#2ca58d',
    spriteHint: 'house_projects',
    dialog: {
      title: 'Fun Projects Lab',
      body: 'Hier liegen deine coolen Experimente, Side Projects und Demos.',
    },
    tags: ['projects', 'creative', 'experiments'],
    district: 'Project Quarter',
    world: {
      x: 176,
      y: 458,
      width: 128,
      height: 96,
      interactRadius: 90,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'projects-list',
        label: 'Projektliste anzeigen',
        type: 'open_modal',
      },
    ],
  },
  {
    id: 'youtube-house',
    name: 'YouTube Studio',
    kind: 'social',
    status: 'coming_soon',
    description: 'Geplantes Studio fuer Videos, Devlogs und Tutorials.',
    accentColor: '#c4302b',
    spriteHint: 'house_youtube',
    dialog: {
      title: 'YouTube Studio',
      body: 'Diese Location ist noch im Bau. Bald erscheinen hier Video-Formate.',
    },
    tags: ['youtube', 'content', 'coming-soon'],
    district: 'Social Lane',
    world: {
      x: 624,
      y: 538,
      width: 96,
      height: 76,
      interactRadius: 80,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'youtube-soon',
        label: 'Coming Soon',
        type: 'coming_soon',
      },
    ],
  },
  {
    id: 'twitter-house',
    name: 'Twitter Kiosk',
    kind: 'social',
    status: 'wip',
    description: 'Kurze Updates, Build-in-public und spontane Gedanken.',
    accentColor: '#1d9bf0',
    spriteHint: 'house_twitter',
    dialog: {
      title: 'Twitter Kiosk',
      body: 'Der Kanal wird vorbereitet. Du kannst ihn spaeter einfach per Glossar aktivieren.',
    },
    tags: ['twitter', 'social', 'wip'],
    district: 'Social Lane',
    world: {
      x: 496,
      y: 548,
      width: 96,
      height: 76,
      interactRadius: 80,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'twitter-open',
        label: 'Twitter oeffnen',
        type: 'open_link',
        href: profileLinks.twitter,
        confirmMessage: 'Twitter in neuem Tab oeffnen?',
      },
    ],
  },
  {
    id: 'npc-guide',
    name: 'Guide NPC',
    kind: 'npc',
    status: 'live',
    description: 'Der Start-NPC erklaert die Welt, Steuerung und Ziele.',
    accentColor: '#69b578',
    spriteHint: 'npc_guide',
    dialog: {
      title: 'Welcome Trainer',
      body: 'Erkunde die Stadt, rede mit NPCs und entdecke Links zu Profil, Projekten und deiner Firma.',
    },
    tags: ['npc', 'tutorial'],
    district: 'Town Square',
    world: {
      x: 496,
      y: 338,
      width: 32,
      height: 40,
      interactRadius: 64,
      visual: 'npc',
      solid: true,
    },
    actions: [
      {
        id: 'guide-controls',
        label: 'Controls anzeigen',
        type: 'open_modal',
      },
    ],
  },
  {
    id: 'npc-recruiter-secret',
    name: 'Recruiter NPC',
    kind: 'npc',
    status: 'live',
    description: 'Geheimer NPC mit Mini-Quest fuer neugierige Besucher.',
    accentColor: '#c3b85f',
    spriteHint: 'npc_recruiter',
    dialog: {
      title: 'Secret Quest',
      body: 'Finde die drei spannendsten Orte in der Stadt. Dann bist du offiziell Explorer.',
    },
    tags: ['npc', 'easter-egg', 'quest'],
    district: 'Hidden Corner',
    world: {
      x: 168,
      y: 566,
      width: 32,
      height: 40,
      interactRadius: 64,
      visual: 'npc',
      solid: true,
    },
    actions: [
      {
        id: 'quest-modal',
        label: 'Quest lesen',
        type: 'open_modal',
      },
    ],
  },
  {
    id: 'sign-controls',
    name: 'Steuerungs-Schild',
    kind: 'sign',
    status: 'live',
    description: 'Kurze Steuerungsinfo fuer Desktop und Mobile.',
    accentColor: '#8b6b4a',
    spriteHint: 'sign_controls',
    dialog: {
      title: 'Controls',
      body: 'Desktop: WASD oder Pfeiltasten. Interaktion: E, Enter, Space oder Klick. Mobile: D-Pad + Interact.',
    },
    tags: ['sign', 'controls'],
    district: 'Town Square',
    world: {
      x: 560,
      y: 352,
      width: 28,
      height: 30,
      interactRadius: 58,
      visual: 'sign',
      solid: false,
    },
    actions: [],
  },
  {
    id: 'sign-about',
    name: 'About-Schild',
    kind: 'sign',
    status: 'live',
    description: 'Ein kurzer Pitch ueber dich und die Idee der Seite.',
    accentColor: '#8d7d58',
    spriteHint: 'sign_about',
    dialog: {
      title: 'About This World',
      body: 'Diese Website ist deine Portfolio-Welt. Jede Location repraesentiert einen Teil deiner Arbeit.',
    },
    tags: ['sign', 'about'],
    district: 'Town Square',
    world: {
      x: 448,
      y: 402,
      width: 28,
      height: 30,
      interactRadius: 58,
      visual: 'sign',
      solid: false,
    },
    actions: [],
  },
  {
    id: 'construction-ruins',
    name: 'Ruinen-Haus',
    kind: 'coming_soon',
    status: 'ruins',
    description: 'Verstaubtes Haus als Platzhalter fuer zukuenftige Releases.',
    accentColor: '#7b7b7b',
    spriteHint: 'house_ruins',
    dialog: {
      title: 'Production Zone',
      body: 'Dieses Haus wird spaeter mit neuem Content repariert und freigeschaltet.',
    },
    tags: ['ruins', 'coming-soon', 'future'],
    district: 'Social Lane',
    world: {
      x: 556,
      y: 542,
      width: 88,
      height: 72,
      interactRadius: 78,
      visual: 'house',
      solid: true,
    },
    actions: [
      {
        id: 'ruins-soon',
        label: 'Noch geschlossen',
        type: 'coming_soon',
      },
    ],
  },
]

export const portfolioById = new Map(portfolioGlossary.map((entry) => [entry.id, entry]))
